# Generated by Django 2.2.1 on 2019-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
