# Generated by Django 2.2.1 on 2019-06-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0002_coupon_coupon_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('coupon_create_at',), 'verbose_name': '優惠卷', 'verbose_name_plural': '優惠卷'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='優惠卷編號'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_title',
            field=models.CharField(max_length=150, verbose_name='優惠卷標題'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='性別'),
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fav_create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加時間')),
                ('coupons', models.ForeignKey(help_text='優惠卷id', on_delete=django.db.models.deletion.CASCADE, to='test_token.Coupon', verbose_name='優惠卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者收藏',
                'verbose_name_plural': '使用者收藏',
                'unique_together': {('user', 'coupons')},
            },
        ),
    ]
