# Generated by Django 2.2.1 on 2019-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0003_auto_20190605_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfav',
            name='coupon_title',
            field=models.CharField(default=1, max_length=150, verbose_name='優惠卷標題'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'coupons', 'coupon_title')},
        ),
    ]
