# Generated by Django 2.2.1 on 2019-06-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0004_auto_20190605_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavs', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'coupons')},
        ),
        migrations.RemoveField(
            model_name='userfav',
            name='coupon_title',
        ),
    ]
