# Generated by Django 2.2.1 on 2019-06-09 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0005_auto_20190605_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
