# Generated by Django 2.2.1 on 2019-06-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0006_auto_20190610_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_img',
            field=models.ImageField(default=1, upload_to='coupons'),
            preserve_default=False,
        ),
    ]
