# Generated by Django 2.2.1 on 2019-06-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_token', '0007_coupon_coupon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
